name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Java 环境
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: 授权 Gradle 执行权限
      run: chmod +x gradlew

    - name: 构建项目
      run: ./gradlew shadowJar

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: build/libs/*.jar
